### ISSUE TITLE
Download not working in iFrame

### ISSUE THREAD

**Issue by ReedGraf** [binary-person/IPdrop#2]
Hi, i was wondering if you could fix the problem when IPdrop is embedded into an iFrame it can send files but can't receive files. Idk enough about JS to fix it myself and submit it to you so I figured I'd ask. Thanks!
-Reed

**Comment by binary-person** [comment]
can you send the error messages in the js console

**Comment by ReedGraf** [comment]
I can't find any evidence of an error on either end of the connection. I think this is because the JS console can't detect anything going on in the iFrame element.

**Comment by binary-person** [comment]
i see the problem now. for some reason, the `content-disposition` header goes missing when it's in an iframe. i will look into it

**Comment by binary-person** [comment]
ok never mind. the cookie is just not being set correctly when in an iframe. i will implement a fix later

**Comment by binary-person** [comment]
fixed
